# Generated by Django 6.0.3 on 2026-03-21 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianprofile',
            options={'verbose_name': '技师', 'verbose_name_plural': '技师'},
        ),
        migrations.AlterModelOptions(
            name='technicianverification',
            options={'verbose_name': '技师认证记录', 'verbose_name_plural': '技师认证记录'},
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='health_cert',
            field=models.FileField(blank=True, null=True, upload_to='verification/health/', verbose_name='健康证'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='id_card_no',
            field=models.CharField(blank=True, max_length=32, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='no_criminal_record',
            field=models.FileField(blank=True, null=True, upload_to='verification/criminal/', verbose_name='无犯罪记录证明'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='service_types',
            field=models.CharField(blank=True, max_length=256, verbose_name='服务类型'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='work_years',
            field=models.IntegerField(default=0, verbose_name='工作年限'),
        ),
        migrations.AddField(
            model_name='technicianverification',
            name='criminal_record',
            field=models.FileField(blank=True, null=True, upload_to='verification/criminal/', verbose_name='无犯罪记录证明'),
        ),
        migrations.AddField(
            model_name='technicianverification',
            name='health_cert',
            field=models.FileField(blank=True, null=True, upload_to='verification/health/', verbose_name='健康证'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='禁用：公共端等同未通过，直接 404', verbose_name='禁用'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='service_areas',
            field=models.CharField(blank=True, help_text='可服务区域（文本，后续可做结构化）', max_length=256, verbose_name='服务区域'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '未通过')], default='pending', max_length=16, verbose_name='认证状态'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='admin_note',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='id_card_back',
            field=models.FileField(blank=True, null=True, upload_to='verification/idcard/back/', verbose_name='身份证反面'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='id_card_front',
            field=models.FileField(blank=True, null=True, upload_to='verification/idcard/front/', verbose_name='身份证正面'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='license_doc',
            field=models.FileField(blank=True, null=True, upload_to='verification/license/', verbose_name='从业资质证明'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '通过'), ('rejected', '驳回')], default='pending', max_length=16, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='technicianverification',
            name='verification_type',
            field=models.CharField(choices=[('idcard', '身份证'), ('health', '健康证'), ('license', '从业资质'), ('criminal', '无犯罪记录'), ('other', '其他')], default='other', max_length=16, verbose_name='认证类型'),
        ),
    ]
