# Generated by Django 6.0.3 on 2026-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_technicianprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='verification/avatar/', verbose_name='形象照片'),
        ),
    ]
