# Generated by Django 6.0.3 on 2026-03-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_technicianprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='推荐技师，优先展示', verbose_name='推荐'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='推荐时间'),
        ),
    ]
