# Generated by Django 6.0.3 on 2026-03-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_technicianprofile_is_recommended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], help_text='用户选择的性别', max_length=8, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='service_areas',
            field=models.TextField(blank=True, help_text='可服务区域，多选，以逗号分隔', verbose_name='服务区域'),
        ),
    ]
