# Generated by Django 6.0.3 on 2026-03-29 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_technicianprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianverification',
            name='license_doc',
        ),
        migrations.CreateModel(
            name='TechnicianLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_file', models.FileField(upload_to='verification/license/', verbose_name='执照文件')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='accounts.technicianprofile')),
            ],
            options={
                'verbose_name': '技师执照',
                'verbose_name_plural': '技师执照',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
