# Generated by Django 6.0.3 on 2026-03-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_technicianverification_license_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='no_criminal_record',
        ),
        migrations.RemoveField(
            model_name='technicianverification',
            name='criminal_record',
        ),
    ]
