# Generated by Django 6.0.3 on 2026-03-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_technicianprofile_no_criminal_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='verification_status',
            field=models.CharField(choices=[('uninitiated', '未发起认证'), ('pending', '待审核'), ('approved', '通过'), ('rejected', '未通过')], default='uninitiated', max_length=16, verbose_name='认证状态'),
        ),
    ]
