# Generated by Django 6.0.4 on 2026-04-17 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_technicianprofile_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128, verbose_name='企业名称')),
                ('business_license', models.FileField(blank=True, null=True, upload_to='verification/organization/', verbose_name='营业执照')),
                ('business_license_number', models.CharField(blank=True, max_length=64, verbose_name='营业执照号')),
                ('contact_person', models.CharField(max_length=64, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='企业地址')),
                ('verification_status', models.CharField(choices=[('uninitiated', '未发起认证'), ('pending', '待审核'), ('approved', '通过'), ('rejected', '未通过')], default='uninitiated', max_length=16, verbose_name='认证状态')),
                ('is_disabled', models.BooleanField(default=False, help_text='禁用：公共端等同未通过', verbose_name='禁用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
            },
        ),
        migrations.CreateModel(
            name='OrganizationTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('active', '已关联'), ('inactive', '已解除')], default='pending', max_length=16, verbose_name='关联状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='accounts.organization')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='accounts.technicianprofile')),
            ],
            options={
                'verbose_name': '机构技师关联',
                'verbose_name_plural': '机构技师关联',
                'unique_together': {('organization', 'technician')},
            },
        ),
    ]
