# Generated by Django 6.0.3 on 2026-03-19 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='catalog_tag_status_43190a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='CNY', max_length=8)),
                ('price_unit', models.CharField(default='per_service', help_text='计价单位（展示用）。', max_length=16)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='用于和分类浏览关联（可选父/子类节点都可以）。', on_delete=django.db.models.deletion.PROTECT, related_name='service_types', to='catalog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='service_types', to='catalog.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'category'], name='catalog_ser_status_ba0839_idx'), models.Index(fields=['name'], name='catalog_ser_name_ecb560_idx')],
                'unique_together': {('name', 'category')},
            },
        ),
    ]
