# Generated by Django 6.0.3 on 2026-03-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片URL')),
                ('link_type', models.CharField(choices=[('category', '分类'), ('listing', '服务详情'), ('url', '网页链接'), ('none', '无跳转')], default='none', max_length=16, verbose_name='跳转类型')),
                ('link_value', models.CharField(blank=True, default='', help_text='分类ID、服务ID或URL', max_length=255, verbose_name='跳转值')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='标题')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': '服务类型', 'verbose_name_plural': '服务类型'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_status_87df08_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='catalog_cat_parent__5307be_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicetype',
            name='catalog_ser_status_ba0839_idx',
        ),
        migrations.RemoveIndex(
            model_name='servicetype',
            name='catalog_ser_name_ecb560_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='catalog_tag_status_43190a_idx',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='基础价格'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='currency',
            field=models.CharField(default='CNY', max_length=8, verbose_name='币种'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=64, verbose_name='服务类型名称'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='price_unit',
            field=models.CharField(default='per_service', help_text='计价单位（展示用）。', max_length=16, verbose_name='计价单位'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='service_types', to='catalog.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['status', 'sort_order'], name='catalog_ban_status_6816ce_idx'),
        ),
    ]
