# Generated by Django 6.0.3 on 2026-03-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='上传轮播图片', null=True, upload_to='banners/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='图片URL'),
        ),
    ]
