# Generated by Django 6.0.3 on 2026-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('icon', models.URLField(blank=True, default='', max_length=500, verbose_name='图标URL')),
                ('link_type', models.CharField(choices=[('category', '分类'), ('listing', '服务详情'), ('url', '网页链接'), ('none', '无跳转')], default='none', max_length=16, verbose_name='跳转类型')),
                ('link_value', models.CharField(blank=True, default='', help_text='分类ID、服务ID或URL', max_length=255, verbose_name='跳转值')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '停用')], default='enabled', max_length=16, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '热门服务',
                'verbose_name_plural': '热门服务',
                'ordering': ['-sort_order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'sort_order'], name='catalog_hot_status_2e54ee_idx')],
            },
        ),
    ]
