# Generated by Django 6.0.3 on 2026-03-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_hotservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='hot_services/icons/', verbose_name='图标'),
        ),
    ]
