"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
import logging

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 统一数据库等配置：先读仓库根目录 .env，再读 backend/.env（后者可覆盖前者）
if load_dotenv:
    _REPO_ROOT = BASE_DIR.parent
    load_dotenv(_REPO_ROOT / ".env")
    load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key-change-me-please-use-longer-string-for-jwt-signing')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if h.strip()
]

_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '').strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt',
    # 不启用 token_blacklist：签发/刷新 JWT 不依赖 OutstandingToken 等表，避免未 migrate 即 500。
    # 登出以客户端丢弃 token 为主；服务端不再维护黑名单。
    'corsheaders',
    'django_filters',
    'drf_yasg',
    # Local apps
    'accounts',
    'catalog',
    'listings',
    'monitoring',
    'admin_portal',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# 仅使用 PostgreSQL，与仓库根目录 .env 及 docker-compose 中 POSTGRES_* 一致（不再使用 SQLite）。
_POSTGRES_DB = os.environ.get("POSTGRES_DB", "jiazheng").strip()
_POSTGRES_USER = os.environ.get("POSTGRES_USER", "duoduo").strip()
_POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD", "")
_POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "localhost").strip()
_POSTGRES_PORT = os.environ.get("POSTGRES_PORT", "5432").strip()
try:
    _POSTGRES_CONN_MAX_AGE = int(os.environ.get("POSTGRES_CONN_MAX_AGE", "0"))
except ValueError:
    _POSTGRES_CONN_MAX_AGE = 0

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _POSTGRES_DB,
        "USER": _POSTGRES_USER,
        "PASSWORD": _POSTGRES_PASSWORD,
        "HOST": _POSTGRES_HOST,
        "PORT": _POSTGRES_PORT,
        "CONN_MAX_AGE": _POSTGRES_CONN_MAX_AGE,
    }
}

if DEBUG:
    _db = DATABASES["default"]
    logging.getLogger(__name__).info(
        "[DB] PostgreSQL 库=%s 主机=%s:%s 用户=%s",
        _db.get("NAME"),
        _db.get("HOST"),
        _db.get("PORT"),
        _db.get("USER"),
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Extra static files (for admin CSS overrides)
STATICFILES_DIRS = [BASE_DIR / "static", BASE_DIR / "staticfiles"]

# Static files collection directory
STATIC_ROOT = BASE_DIR / 'collected_static'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media uploads (for technician verification files, if you later enable uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 缓存：无 Redis 时 USE_REDIS=false（如部分 CI）使用本地内存
# 注意：管理后台登录验证码依赖 cache；若用 gunicorn 多 worker，必须启用 Redis 等进程间共享缓存，
# 否则 LocMemCache 下各 worker 内存独立，验证码会表现为「总是错误」或「已过期」。
_use_redis = os.environ.get('USE_REDIS', 'true').lower() == 'true'
if _use_redis:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': os.environ.get('REDIS_URL', 'redis://localhost:6379/0'),
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 100
                },
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-jiazheng',
        }
    }

# DRF
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    # 未启用 token_blacklist 时，轮换刷新会在无黑名单下留下安全隐患；关闭轮换，沿用同一 refresh 至过期。
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# CORS：生产环境在 .env 中关闭 CORS_ALLOW_ALL_ORIGINS 并配置 CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'true').lower() == 'true'
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS = [
        o.strip()
        for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if o.strip()
    ]

# OpenAPI 文档（生产可设 ENABLE_API_DOCS=false）
ENABLE_API_DOCS = os.environ.get('ENABLE_API_DOCS', 'true').lower() == 'true'

# 公共分类树：服务端缓存秒数，并设置 Cache-Control max-age（客户端/开发者工具也可能跟缓存）。
# 设为 0：不写服务端缓存，且响应带 no-store/no-cache（适合联调、分类管理后立即验证）。
# 分类在后台保存/删除时会主动清除服务端缓存键，但若客户端仍留着旧响应，可设 0 或清工具缓存。
PUBLIC_CATEGORY_TREE_CACHE_SECONDS = int(os.environ.get('PUBLIC_CATEGORY_TREE_CACHE_SECONDS', '300'))


# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'listings': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# 确保日志目录存在
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR, exist_ok=True)
