# Generated by Django 6.0.3 on 2026-04-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('key', models.CharField(blank=True, default='', max_length=64, verbose_name='页面键')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='路径')),
                ('icon', models.TextField(blank=True, default='', verbose_name='图标')),
                ('is_section', models.BooleanField(default=False, verbose_name='是否分组')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('allow_all_staff', models.BooleanField(default=True, verbose_name='允许所有管理员')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='admin_menus', to=settings.AUTH_USER_MODEL, verbose_name='指定可见用户')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admin_portal.adminmenu', verbose_name='父菜单')),
            ],
            options={
                'db_table': 'admin_menu',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
