# Generated by Django 6.0.3 on 2026-03-19 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMonitoringCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('reached', 'Reached'), ('not_reached', 'Not reached'), ('invalid', 'Invalid / mismatch')], default='not_reached', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_monitoring_calls', to='listings.listing')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_monitoring_calls', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_monitoring_calls', to='accounts.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CallAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, default='mini_program', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='listings.listing')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to='accounts.technicianprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'called_at'], name='monitoring__user_id_0409f0_idx'), models.Index(fields=['technician', 'called_at'], name='monitoring__technic_ecfa2d_idx')],
            },
        ),
    ]
