# Generated by Django 6.0.3 on 2026-03-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmonitoringcall',
            options={'verbose_name': '管理员监控拨打', 'verbose_name_plural': '管理员监控拨打'},
        ),
        migrations.AlterModelOptions(
            name='callattempt',
            options={'verbose_name': '拨打留痕', 'verbose_name_plural': '拨打留痕'},
        ),
        migrations.AlterField(
            model_name='adminmonitoringcall',
            name='result',
            field=models.CharField(choices=[('reached', '接通'), ('not_reached', '未接通'), ('invalid', '信息不符/无效')], default='not_reached', max_length=16),
        ),
    ]
