# Generated by Django 6.0.3 on 2026-03-19 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Audit'), ('published', 'Published'), ('rejected', 'Rejected'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('audit_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.category')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.technicianprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'category'], name='listings_li_status_5468e2_idx'), models.Index(fields=['technician', 'status'], name='listings_li_technic_abcef3_idx')],
            },
        ),
    ]
