# Generated by Django 6.0.3 on 2026-03-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tag_servicetype'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='listings', to='catalog.servicetype'),
        ),
    ]
