# Generated by Django 6.0.3 on 2026-03-23 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_technicianprofile_avatar'),
        ('catalog', '0004_add_banner_image'),
        ('listings', '0002_listing_services'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': '发布信息', 'verbose_name_plural': '发布信息'},
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_status_5468e2_idx',
        ),
        migrations.RemoveIndex(
            model_name='listing',
            name='listings_li_technic_abcef3_idx',
        ),
        migrations.AlterField(
            model_name='listing',
            name='audit_note',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='audited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='cover_url',
            field=models.URLField(blank=True, default='', verbose_name='封面图 URL'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='listings', to='catalog.servicetype', verbose_name='服务类型'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('rejected', '驳回'), ('disabled', '下架')], default='draft', max_length=16, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='accounts.technicianprofile', verbose_name='技师'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
    ]
