# Generated by Django 6.0.3 on 2026-03-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_cover_urls_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='service_areas',
            field=models.TextField(blank=True, help_text='可服务区域，多选，以逗号分隔', verbose_name='服务区域'),
        ),
    ]
