# Generated by Django 6.0.3 on 2026-03-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_service_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
    ]
