# Generated by Django 6.0.3 on 2026-03-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contact_info',
            field=models.CharField(blank=True, help_text='服务的联系方式，不一定是注册手机号', max_length=128, verbose_name='联系方式'),
        ),
    ]
