# Generated by Django 6.0.3 on 2026-03-29 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_contact_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('published', '已发布'), ('rejected', '驳回'), ('disabled', '下架')], max_length=16, verbose_name='审核状态')),
                ('audit_note', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='listings.listing')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '服务审核记录',
                'verbose_name_plural': '服务审核记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
